baseURL = "https://marcolee1107.github.io/"
languageCode = "zh-tw"
DefaultContentLanguage = "tw"
title = "Website of Marco Lee"
theme = "anatole"
summarylength = 6
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "--"

[params]
title = "I'm Marco Lee"
author = "Marco Lee"
description = "漫步在業餘和隨性的興緻，也像是一項項的挑戰"
profilePicture = "images/profile3.png"
keywords = "blockchain, hugo"
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["posts"]
images = ["images/site-feature.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/marcolee1107/"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:marcolinking@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"